export const TransactionList = [{
    date: "June 06, 2023",
    type: "Sent",
    name: "Amadej Baar",
    amount: "157.34",
    currency: "USD",
},
{
    date: "June 01, 2023",
    type: "Sent",
    name: "Meritxell Paredes",
    amount: "200000",
    currency: "KRW",
},
{
    date: "April 09, 2023",
    type: "Received",
    name: "Dumi Schreiber",
    amount: "250.00",
    currency: "USD",
},
{
    date: "April 09, 2023",
    type: "Sent",
    name: "Abdastartus Hennig",
    amount: "1234.00",
    currency: "GBP",
},
{
    date: "April 09, 2023",
    type: "Cancelled",
    name: "Abdastartus Hennig",
    amount: "12.34",
    currency: "GBP",
},
{
    date: "March 10, 2023",
    type: "Sent",
    name: "Saxa Lawrenz",
    amount: "9999.99",
    currency: "USD",
},
{
    date: "February 03, 2023",
    type: "Sent",
    name: "Sanjeet Hayes",
    amount: "102.00",
    currency: "USD",
},
{
    date: "February 03, 2023",
    type: "Cancelled",
    name: "Sanjeet Hayes",
    amount: "1.02",
    currency: "USD",
},
{
    date: "January 27, 2023",
    type: "Received",
    name: "Amanda Heaghra",
    amount: "783.56",
    currency: "EUR",
},
{
    date: "January 26, 2023",
    type: "Sent",
    name: "Mukhtar Willoughby",
    amount: "1203.53",
    currency: "AUD",
},
{
    date: "December 10, 2022",
    type: "Sent",
    name: "Adolph Pasternack",
    amount: "50164500",
    currency: "VND",
},
{
    date: "November 08, 2022",
    type: "Sent",
    name: "Cai Aoki",
    amount: "890000",
    currency: "KRW",
}]